# name: Build Production Ireland RP-Indexer
# on:
#   push:
#     tags:
#       - 'v*.*.*'
#       - '!v*.*.*-staging*'
#       - '!v*.*.*-develop*'
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     environment: 
#       name: production-ireland
#     steps:
#       - name: Set output
#         id: vars
#         run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/}|cut -d'/' -f3);
#       - name: Check out the repo
#         uses: actions/checkout@v2
#         with: 
#           ref: main
#       - name: Check out the repo
#         uses: actions/checkout@v2
#         with:
#           ref:  feature/build
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to ECR
#         uses: docker/login-action@v1 
#         with:
#           registry: 452158872079.dkr.ecr.eu-west-1.amazonaws.com
#           username: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       - name: Build and push - Indexer Image
#         id: docker_build1
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: docker/Dockerfile
#           push: true
#           tags: 452158872079.dkr.ecr.eu-west-1.amazonaws.com/rp-indexer-rapidpro:${{ steps.vars.outputs.tag }}
#           no-cache: true